name: benchmark

on:
  schedule:
    - cron: '0 0 * * 1,5'
  push: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Benchmark
      run: |
        go test -v -cpu=4 -run=none -bench=. -benchtime=10s -benchmem bmark_test.go | tee x
	perl scripts/resultsToMarkdown.pl x


